ALTER TABLE user_topics ADD COLUMN IF NOT EXISTS updated TIMESTAMP DEFAULT NOW();

CREATE TABLE IF NOT EXISTS points_movement (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id uuid REFERENCES users(id),
    amount INTEGER,
    description TEXT,
    created TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS points INTEGER NOT NULL DEFAULT 0;

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS deadline INTEGER NOT NULL DEFAULT 3;