version: "3.9"

services:
  pg:
    image: $CI_REGISTRY/binom.study/binom/pg:${CI_COMMIT_BRANCH}
    command: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres/data:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: postgres
      POSTGRES_DB_NAME_TEST: postgres_test
      PGDATA: /data/postgres
  nginx:
    image: $CI_REGISTRY/binom.study/binom/nginx:${CI_COMMIT_BRANCH}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - golang
    volumes:
      - /etc/letsencrypt:/etc/ssl
    environment:
      HOST: binom.school
      SSL_CERT: /etc/ssl/live/binom.school/fullchain.pem
      SSL_CERT_KEY: /etc/ssl/binom.school/privkey.pem
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-size: "10m"
        max-file: "1000"
  golang:
    image: $CI_REGISTRY/binom.study/binom/golang:${CI_COMMIT_BRANCH}
    command: ["./scripts/wait-for-it.sh", "pg:5432", "--", "/goapp/main"]
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - pg
    environment:
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_PATH: /goapp/upload
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: postgres
      POSTGRES_HOST: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: postgres
      POSTGRES_DB_NAME_TEST: postgres_test
      HOST: binom.school
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-size: "10m"
        max-file: "1000"
